---
name: Download Release Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
      
      - name: Download release
        uses: actions/download-artifact@v2
        with:
          name: storage
          repository: caffreyu/random
          ref: v0.0.1
      
      - name: List all the files
        runs: |
          echo ./*
