---
name: Download Release Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
      
      - name: Download and unpack downloaded file
        shell: bash
        run: |
          wget https://github.com/caffreyu/random/archive/refs/tags/v0.0.1.tar.gz -O download.tar.gz
          tar -xzf download.tar.gz
      
      - name: List all the files
        shell: bash
        run: |
          echo ./*
