---
name: Download Release Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
      
      - name: Download and unpack downloaded file
        shell: bash
        run: |
          wget https://github.com/caffreyu/random/archive/refs/tags/v0.0.1.tar.gz -O download.tar.gz
          tar -xzf download.tar.gz
      
      - name: List all the files
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install tree
          tree
      
      - name: Find the directory name
        shell: bash
        run: |
          if [ -d random-* ]; then
            echo "Found the downloaded directory"
          else
            echo "Failed to find the downloaded directory"
            exit 1
          fi
          RANDOM_DIR=$(find . -type d -name "random*" | head -n 1)
          echo "Found directory: $RANDOM_DIR"
      
      - name: Arrange files
        shell: bash
        run: |
          mv $RANDOM_DIR/docs ./docs
          rm -rf $RANDOM_DIR
          cat ./docs/date.txt

          
          
