---
name: Test trigger event action in Random

on:
  repository_dispatch:
    types:
      - test-workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          ref: "${{ github.event.client_payload.ref }}"
      
      - name: Echo hello world
        run: |
          echo hello world
      